### ISSUE TITLE
Tirupati vs. Cologne Edition Text Comparison

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/VCP#1]
It would be good to compare both editions with http://samskrtam.ru/fuzzy-error-finding/ or http://samskrtam.ru/textdiff-dictionary/ - a lot of interesting details should come up. Including the 4000 missing, undeciphered letters from the Cologne edition http://www.sanskrit-lexicon.uni-koeln.de/scans/VCPScan/2013/web/index.php
I've converted the Preface of Tirupati edition to Unicode, as well as the abbreviations - it's a good, clean and ready list in Devanagari now (was in Yogesh encoding).
Still need to push the WX to UTF8 covnerter, so you can try it on your own, Jim.
Original Tirupati files come from a CD rip in my Dropbox https://www.dropbox.com/sh/0p1a17yybllkilx/jNnp8GsVsB

**Comment by drdhaval2785** [comment]
#14 and #15 track this issue further. Closing.
