### ISSUE TITLE
New VCP scans

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/VCP#13]
There are now new scanned images for the Vacaspatyam dictionary at Cologne.

They are available via the links within the VCP displays, or directly using the servepdf
program:

https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/servepdf.php?dict=vcp&page=5441

As a reminder, servepdf also can be used with the 'key' parameter:

https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/servepdf.php?dict=vcp&key=fzi&input=slp1

or 
https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/servepdf.php?dict=vcp&key=ṛṣiproktā&input=iast

The previous images can still be accessed by urls like:
https://www.sanskrit-lexicon.uni-koeln.de/scans/VCPScan/2013/web/webtc/servepdf.php?page=5441

This 2013 display doesn't support the 'key' method.

**Comment by funderburkjim** [comment]
These new images are often less 'smudged' than the older images; it is hoped that they
will facilitate comparisons between the digitization and printed text.

The images were suggested by @Andhrabharati in discussion at https://github.com/sanskrit-lexicon/csl-orig/issues/469.

**Comment by funderburkjim** [comment]
## image sources

The pdfs were obtained from https://www.scribd.com/ and https://archive.org with
the following urls.

* [01](https://archive.org/download/vacaspatyaacomprehensivesanscritdictionaryintenpartspartiaap_41_i/Vacaspatya-A-Comprehensive-Sanscrit-Dictionary-in-Ten-Parts-Part-I-a-AP.pdf) archive.org a-AP
* [02](https://www.scribd.com/document/106534837/Vacaspatya-A-Comprehensive-Sanscrit-Dictionary-in-Ten-Parts-Part-II-AP-Ashu-Calcutta-1873-600dpi-Lossless)  scribd AP-Ashu
* [03](https://archive.org/download/vacaspatyaacomprehensivesanscritdictionaryintenpartspartiiiashuaan_751_N/Vacaspatya-A-Comprehensive-Sanscrit-Dictionary-in-Ten-Parts-Part-III-Ashu-Aan.pdf)  archive.org Ashu-Aan
* [04](https://archive.org/download/vacaspatyaacomprehensivesanscritdictionaryintenpartspartivaanindriya_140_/Vacaspatya-A-Comprehensive-Sanscrit-Dictionary-in-Ten-Parts-Part-IV-Aan-Indriya.pdf)  archive.org Aan-Indriya
* [05](https://www.scribd.com/document/106537136/Vacaspatya-A-Comprehensive-Sanscrit-Dictionary-in-Ten-Parts-Part-v-Indh-Upa-Calcutta-1874-600dpi-Lossless)  scribd Indh-Upa
* [06](https://archive.org/download/vacaspatyaacomprehensivesanscritdictionaryintenpartspartviupartu_369_F/Vacaspatya-A-Comprehensive-Sanscrit-Dictionary-in-Ten-Parts-Part-VI-Upa-Rtu.pdf) archive.org Upa-Rtu
* [07](https://www.scribd.com/document/106538853/Vacaspatya-A-Comprehensive-Sanscrit-Dictionary-in-Ten-Parts-Part-VII-Rtu-Kaphi-Calcutta-1875-600dpi-Lossless)  scribd Rtu-Kaphi
* [08](https://www.scribd.com/document/106539695/Vacaspatya-A-Comprehensive-Sanscrit-Dictionary-in-Ten-Parts-Part-VIII-Kaph-Kaaya-Calcutta-1875-600dpi-Lossless)  scribd Kaph-Kaaya
* [09](https://www.scribd.com/document/106540628/Vacaspatya-A-Comprehensive-Sanscrit-Dictionary-in-Twenty-Parts-Part-IX-Kaaya-Kush-Calcutta-1875-600dpi-Lossless)  scribd Kaaya-Kush
* [10](https://www.scribd.com/document/106541822/Vacaspatya-A-Comprehensive-Sanscrit-Dictionary-in-Twenty-Parts-Part-X-Kus-Kshe-Calcutta-1876-600dpi-Lossless)  scribd Kus-Kshe
* [11](https://www.scribd.com/document/106542645/Vacaspatya-A-Comprehensive-Sanscrit-Dictionary-in-Twenty-Parts-Part-XI-Kshe-Grih-Calcutta-1877-600dpi-Lossless)  scribd Kshe-Grih
* [12](https://www.scribd.com/document/106543529/Vacaspatya-A-Comprehensive-Sanscrit-Dictionary-in-Twenty-Parts-Part-XII-Grih-Catu-Calcutta-1878-600dpi-Lossless)  scribd Grih-Catu
* [13](https://www.scribd.com/document/106544248/Vacaspatya-A-Comprehensive-Sanscrit-Dictionary-in-Twenty-Parts-Part-XIII-Catu-Jijna-Calcutta-1879-600dpi-Lossless)  scribd Catu-Jijna
* [14](https://www.scribd.com/document/106544810/Vacaspatya-A-Comprehensive-Sanscrit-Dictionary-in-Twenty-Parts-Part-XIV-Jit-Tiiy-Calcutta-1879-600dpi-Lossless)  scribd Jit-Tiiy
* [15](https://www.scribd.com/document/106546555/Vacaspatya-A-Comprehensive-Sanscrit-Dictionary-in-Twenty-Parts-Part-XV-Tish-Diks-Calcutta-1880-600dpi-Lossless)  scribd Tish-Diks
* [16](https://www.scribd.com/document/106547356/Vacaspatya-A-Comprehensive-Sanscrit-Dictionary-in-Twenty-Parts-Part-XVI-Diiksh-Dvaar-Calcutta-1881-600dpi-Lossless)  scribd Diiksh-Dvaar
* [17](https://www.scribd.com/document/106547923/Vacaspatya-A-Comprehensive-Sanscrit-Dictionary-in-Twenty-Parts-Part-XVII-DhaT-Niya-Calcutta-1881-600dpi-Lossless)  scribd DhaT-Niya
* [18](https://www.scribd.com/document/106548830/Vacaspatya-A-Comprehensive-Sanscrit-Dictionary-in-Twenty-Parts-Part-XVIII-Niy-Paarv-Calcutta-1882-600dpi-Lossless)  scribd Niy-Paarv
* [19](https://www.scribd.com/document/106545750/Vacaspatya-A-Comprehensive-Sanscrit-Dictionary-in-Twenty-Parts-Part-XIX-Paarv-Badhi-Calcutta-1882-600dpi-Lossless)  scribd Paarv-Badhi
* [20](https://www.scribd.com/document/106620770/Vacaspatya-A-Comprehensive-Sanscrit-Dictionary-in-Twenty-Parts-Part-XX-Bandh-Rase-Calcutta-1883-600dpi-Lossless)  scribd Bandh-Rase
* [21](https://www.scribd.com/document/106620808/Vacaspatya-A-Comprehensive-Sanscrit-Dictionary-in-Twenty-Two-Parts-Part-XXI-Rase-Vrat-Calcutta-1883-600dpi-Lossless)  scribd Rase-Vrat
* [22](https://www.scribd.com/document/106620874/Vacaspatya-A-Comprehensive-Sanscrit-Dictionary-in-Twenty-Two-Parts-Part-XXII-Vrat-Hve-Calcutta-1884-600dpi-Lossless)  scribd Vrat-Hve


Note: The archive.org links are to the pdfs, and could be used with curl to download the pdf.
The scribd links are to download pages and  AFAIK there are no direct links to the pdfs, so
curl or other automation tools are not available .

**Comment by funderburkjim** [comment]
## processing

The above 22 pdfs were processed to 5442 one-page pdfs appropriately named.
* Adobe Acrobat 9 was used to extract the individual pages from each pdf
* Each of the 22 pdfs was examined to determine which of the pdf pages to keep
   * a few Title pages at the beginning and blank or other pages at the end were 
     identified to be ignored
* Some simple Python programs renamed these 5442 files into the form 'pgxxxx.pdf'
* These files were uploaded to Cologne (using scp). They were put into
   scans/VCPScan/2019/web/pdfpages directory
* The csl-apidev servepdf program was altered so requests for VCP scanned images would
   refer to the 2019/web/pdfpages source.

**Comment by gasyoun** [comment]
> new scanned images for the Vacaspatyam dictionary at Cologne.

Good news.

In my Chrome on Win 7 still some images do not load (at least initially properly.

![scands](https://user-images.githubusercontent.com/80761/111040235-0bc3f900-8443-11eb-9ddf-234c17d52386.JPG)

**Comment by Andhrabharati** [comment]
> * [01](https://archive.org/download/vacaspatyaacomprehensivesanscritdictionaryintenpartspartiaap_41_i/Vacaspatya-A-Comprehensive-Sanscrit-Dictionary-in-Ten-Parts-Part-I-a-AP.pdf) archive.org a-AP
> 
> * [03](https://archive.org/download/vacaspatyaacomprehensivesanscritdictionaryintenpartspartiiiashuaan_751_N/Vacaspatya-A-Comprehensive-Sanscrit-Dictionary-in-Ten-Parts-Part-III-Ashu-Aan.pdf)  archive.org Ashu-Aan
> 
> * [04](https://archive.org/download/vacaspatyaacomprehensivesanscritdictionaryintenpartspartivaanindriya_140_/Vacaspatya-A-Comprehensive-Sanscrit-Dictionary-in-Ten-Parts-Part-IV-Aan-Indriya.pdf)  archive.org Aan-Indriya
> 
> * [06](https://archive.org/download/vacaspatyaacomprehensivesanscritdictionaryintenpartspartviupartu_369_F/Vacaspatya-A-Comprehensive-Sanscrit-Dictionary-in-Ten-Parts-Part-VI-Upa-Rtu.pdf) archive.org Upa-Rtu


@funderburkjim  seems to have missed seeing my message about the scribd links (as suggested at sanskrit-lexicon/csl-orig#469.)

Here they are again-
Vol.1
https://www.scribd.com/doc/106533946/Vacaspatya-A-Comprehensive-Sanscrit-Dictionary-in-Ten-Parts-Part-I-a-AP-Calcutta-1873-600dpi-Lossless

Vol.3
https://www.scribd.com/document/106535560/Vacaspatya-A-Comprehensive-Sanscrit-Dictionary-in-Ten-Parts-Part-III-Ashu-Aan-Calcutta-1873-600dpi-Lossless

Vol.4
https://www.scribd.com/document/106536262/Vacaspatya-A-Comprehensive-Sanscrit-Dictionary-in-Ten-Parts-Part-IV-Aan-Indriya-Calcutta-1874-600dpi-Lossless

Vol.6
https://www.scribd.com/document/106537943/Vacaspatya-A-Comprehensive-Sanscrit-Dictionary-in-Ten-Parts-Part-VI-Upa-Rtu-Calcutta-1875-600dpi-Lossless

**Comment by Andhrabharati** [comment]
BTW, I am not able to get the www.sanskrit-lexicon.uni-koeln.de links opened since morning.

Any issues in the server?

**Comment by funderburkjim** [comment]
Re 1,3,4,6 

I had already downloaded these 4 volumes from archive.org before seeing your links to scribd.

I suppose that if we find that these 4 from archive are inferior to the ones from scribd,
I could redo them.

**Comment by Andhrabharati** [comment]
I guess all those are the same, taken from google books!

**Comment by funderburkjim** [comment]
Re problem with www.sanskrit-lexicon.uni-koeln.de links.

If the problem persists,  please send me a specific link that does not work.

**Comment by funderburkjim** [comment]
Re the problem with blank spot in https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/servepdf.php?dict=vcp&key=fzi&input=slp1  

with chrome/windows 7

I'm currently using Edge browser Windows 10.  Above url displays properly (no blank spot).

Also no problem with Chrome browser on Windows 10 for this page.

**Comment by Andhrabharati** [comment]
The whole site, not any particular links.

Checked on pc, in firefox & opera; and on my android phone, in firefox & chrome.

None working, giving "timed out" error.

No issue in the settings, every other site is opening properly in all these 4 cases.

**Comment by funderburkjim** [comment]
Wow!  Don't know why you can't connect.  The site is up for me (I live in Pennsylvania in US).

**Comment by funderburkjim** [comment]
@drdhaval2785   Have you had any problems connecting to https://www.sanskrit-lexicon.uni-koeln.de/ ?

**Comment by Andhrabharati** [comment]
just checked on pc, both firefox & opera could open the cologne links with VPN.

so it could be something to do with ISPs.

will again try tomorrow morning in normal mode.

**Comment by funderburkjim** [comment]
> Where are they  (python programs) ?

[This gist](https://gist.github.com/funderburkjim/f249284bf19804aaea7eb88e2fa4808d)
contains a readme.txt file and source of two python programs.
It has a detailed description of how the single-page pdfs were created.

**Comment by gasyoun** [comment]
> It has a detailed description of how the single-page pdfs were created.

Thanks, so detailed!

**Comment by Andhrabharati** [comment]
big effort put by Jim, in creating pagewise pdfs.

all this could be done very easily with the acrobat 9 itself! (just combine all the 22 pdfs as a single file, and then extract the pages as individual pdfs- with whatever file naming one requires)

**Comment by gasyoun** [comment]
> all this could be done very easily with the acrobat 9 itself!

Not the naming, impossible.

**Comment by drdhaval2785** [comment]
Scans are on air. Closing.
