### ISSUE TITLE
Renaming VCP to VCPTE

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/VCP#2]
Since the files here are from the Tirupati edition of VCP, and not to the current Cologne sanskrit-lexicon VCP, suggest renaming this repository something else, such as VCPTE. Then, create another VCP that will have file from sanskrit-lexicon version.  
Alternately, since it is hoped that the two editions may be merged, these files (especially the underlying data a.txt) might be put into a folder within VCP, if this is possible with Github.

**Comment by drdhaval2785** [comment]
I am not sure about this request. Closeable @funderburkjim ?

**Comment by funderburkjim** [comment]
Agree with closing.

**Comment by gasyoun** [comment]
A subfolder would not be enough?
