### ISSUE TITLE
herasva> heramba

### ISSUE THREAD

**Issue by Shalu411** [sanskrit-lexicon/VCP#4]
Namaste
Just submitted a correction- heramba 
Here is the snippet (म is protruded to become स) But in meaning explanation it is clear.
![heramba](https://cloud.githubusercontent.com/assets/6392207/4115324/84f46c68-3276-11e4-9438-187b535dac07.JPG)

**Comment by drdhaval2785** [comment]
'heramba' works on Cologne site, and 'herasva' does not. Closing.
