### ISSUE TITLE
Tirupati v. Cologne example

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/VCP#6]
Recently, a user submitted a correction to the Cologne edition of Vacaspatyam, under
headword rAmayaRa.  The error was in line 361875 of vcp.txt:

```
<HI>{@rAmAyaRa@}¦ na0 . rABasyAyanaM caritamaDikftya kfto granTo'R
```

rABasyAyanaM should be rAmasyAyanaM (= rAmasya Ayanam  = of Rama, the going)

In the Scharf edition of the Tirupati edition of Vacaspatyam  (vac.txt), the spelling is correct: (line
39234 of vac1.txt):

```
rAmAyaRa    39234    %rAmAyaRa% na0. <vg>rAmasyAyanaM caritamaDikftya kfto 
granTaH</vg> <vkr>aR.</vkr>     ETC
```

In the file *len1.txt' (of directory vac-vcp-cmp1 of this repository),  there is a 'fuzzy' comparison 
between ALL the headwords of the two editions. 

The comparison statistics for headword rAmAyaRa reads as:

 4805  4835  4084  3932   **152** rAmAyaRa:39234,39234 == rAmAyaRa:361785,361874

where the `152` indicates 'a lot' of difference for this headword.

Many headwords (11332)  are rated to be identical. 

Many headwords are only very slightly different (3366).

I hope some knowledgeable Sanskritist will be intrigued by the idea of using this comparison
to improve  both versions of this dictionary.   It's a big task, and would be a valuable contribution.

**Comment by Shalu411** [comment]
नमस्ते
It is --- B > m correction--- got it. 
But the right breaking will be this- 
रामायणम्- रामस्य अयनम् 
not आयनम्

**Comment by gasyoun** [comment]
Where is the 3366 list? Can we bold the letters that are different?

**Comment by funderburkjim** [comment]
@Shalu411   Thank you for the correction.  How can I understand why 'ayana' is the answer and
'Ayana' is wrong?

**Comment by funderburkjim** [comment]
The 3366 number was derived by a selection of records from the len1.txt file mentioned above; the
selected records are those matching `<space>1<space>'.   This file does not have the records to
view for comparison, but only references to the headwords and to the location of the the comparable
records in the two files vac1.txt (Tirupati) and vcp1.txt (Cologne).

If someone gets interested in the project, I can develop useful tools for the comparisons, including
possibly highlighting (bolding) the differences.

**Comment by drdhaval2785** [comment]
#15 takes care of all differences. Closing this issue.
